name: "blip_vqa_text_decoder"
backend: "python"

max_batch_size: 0

input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [-1, -1, -1, 768 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_STRING
    dims: [-1]
  }
]

instance_group [{ kind: KIND_GPU, gpus:[0] }]
