name: "blip_vqa"
backend: "python"

input [
  {
    name: "IMAGE"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
input [
  {
    name: "QUESTION"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
output [
  {
    name: "ANSWER"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

instance_group [{ kind: KIND_GPU, gpus:[0] }]
