name: "blip_vqa_bls"
backend: "python"

max_batch_size: 1

input [
  {
    name: "INPUT0"
    data_type: TYPE_STRING
    dims: [-1]
  }
]
input [
  {
    name: "INPUT1"
    data_type: TYPE_STRING
    dims: [-1]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [-1]
  }
]

instance_group [{ kind: KIND_GPU, gpus:[0] }]
